---
# !!! this taking minutes

# check for a cached storage base file.
#   "/var/lib/libvirt/images/{{ fqdn }}-base.qcow2"
# don't bother reinstalling if it exists.
# check for an image file.
#   "/var/lib/libvirt/images/{{ fqdn }}.qcow2"
# don't overwrite it.

# check for a cached storage base file.
- name: Look for the machine base volume.
  ansible.builtin.include_tasks:
    file: check_host.yml

- name: "Does the volume '/var/lib/libvirt/images/{{ fqdn }}.qcow2' already exist?"
  ansible.builtin.debug:
    verbosity: 1
    msg: "volume_image_file_exists: {{ volume_image_file_exists }}"

- name: "Does the base volume '/var/lib/libvirt/images/{{ fqdn }}.qcow2' already exist?"
  ansible.builtin.debug:
    verbosity: 1
    msg: "volume_base_file_exists: {{ volume_base_file_exists }}"
