# Create bridge and nmcli connection config.
# For CLI equivalents, see comments in public-linux-bridge.yml

- name: Set up the private bridge
  vars:
    network_connections:
      - name: "{{ lab_nmcli_name }}"
        state: up
        type: bridge
        interface_name: "{{ lab_bridge_name }}"
        ip:
          address:
          - "{{ lab_bridge_ip_cidr }}"
        #mac: "{{ lab_bridge_mac }}"
  ansible.builtin.include_role:
    # RHEL
    # name: rhel-system-roles.network
    # Fedora
    name: linux-system-roles.network
